-- create a database called 'demo_db' in the instance of PostgreSQL
-- create database demo_db;

-- and then run the SQL script within demo_db

drop schema if exists client cascade;

create schema client;

create table client.client
(
    id    bigint generated by default as identity
        constraint client_pk
            primary key,
    first_name  varchar(32) not null,
    last_name  varchar(32) not null,
    email varchar(32) not null,
    gender int2 not null,   -- 0: female, 1: male, 2: others
        constraint email
            unique (email)  -- multi-column  candidate key
);

insert into client.client (first_name, last_name, email, gender)
    values ('Clyde', 'Burris', 'cburris0@mapquest.com', 1),
           ('Aline', 'Abela', 'aabela1@php.net', 0),
           ('Deina', 'Potte', 'dpotte2@flickr.com', 0),
           ('Malia', 'McGreil', 'mmcgreil3@hibu.com', 0),
           ('Terence', 'Crampin', 'tcrampin4@tripod.com', 1),
           ('Karissa', 'MacElane', 'kmacelane5@guardian.co.uk', 0),
           ('Margi', 'Newby', 'mnewby6@harvard.edu', 2),
           ('Dom', 'Sinclair', 'dsinclair7@g.co', 1),
           ('Gordie', 'Sperling', 'gsperling8@biblegateway.com', 1),
           ('Elysha', 'Shillum', 'eshillum9@prweb.com', 0),
           ('Benton', 'Slator', 'bslatora@so-net.ne.jp', 1),
           ('Clare', 'Rigts', 'crigtsb@elpais.com', 1),
           ('Winnie', 'Ramsdell', 'wramsdellc@bloomberg.com', 0),
           ('Dionne', 'Lomasna', 'dlomasnad@posterous.com', 2),
           ('Adorne', 'Goundrill', 'agoundrille@nih.gov', 0),
           ('Cesare', 'MacAnespie', 'cmacanespief@nasa.gov', 1),
           ('Leodora', 'Thatcham', 'lthatchamg@prnewswire.com', 0),
           ('Ahmad', 'Simmings', 'asimmingsh@is.gd', 1),
           ('Cchaddie', 'Twigley', 'ctwigleyi@about.com', 1),
           ('Jacquelyn', 'Robbey', 'jrobbeyj@wikispaces.com', 2);

drop schema if exists user_info cascade;

create schema user_info;

create table user_info.user
(
    "id"    bigint generated by default as identity
        constraint client_pk
            primary key,
    "username"  varchar(32) not null default 'null',
    "nickname"  varchar(32) not null default 'null',
    "password" varchar(64) not null default 'null',
    "status" int2 default 0, -- 0: normal, 1: suspended
    "email" varchar(32) default null,
    "mobile" varchar(20) default null,
    "gender" int2 default null,   -- 0: female, 1: male, 2: others
    "avatar" varchar(128) default null,
    "user_type" int2 not null default 1,  -- 0: admin, 1: normal
    "create_by" bigint default null,
    "create_time" timestamp with time zone default null,
    "update_by" bigint default null,
    "update_time" timestamp with time zone default null,
    "delete_flag" int2 default 0,
        constraint email
            unique (email)  -- multi-column  candidate key
);

insert into user_info.user ("username", "nickname", "password", "user_type")
    values ('admin', 'admin', '$2a$12$DkLEN8MwZXTLVFPDHNgMfO118HPmYlURSz3BcHbE9JRrYG5VJwr2C', 0),
           ('jasonqiu', 'jasonqiu', '$2a$12$sagAtXPRINjyVAO2KVheGuLzaSTbJ7DXl/nwMUfQxyL91ZtVfYh32', 1);
