package com.jasonqiu.springbootreactdemo.entity;

import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.Data;

/**
 * No constructors will be generated by @Data
 * since some explicitly written constructors already exist
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ResponseResult<T> {
    /**
     * status code
     */
    private Integer code;

    /**
     * error message for frontend
     */
    private String msg;

    /**
     * data results from queries
     */
    private T data;

    public ResponseResult(Integer code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public ResponseResult(Integer code, T data) {
        this.code = code;
        this.data = data;
    }

    public ResponseResult(Integer code, String msg, T data) {
        this.code = code;
        this.msg = msg;
        this.data = data;
    }

}
