server:
  port: 8091
spring:
  application:
    name: spring-react-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/demo_db
    username: postgres
    password: datagrip02
  redis:
    host: redis-master
    port: 6379
    password: foobared
springdoc:
  api-docs:
    path: /api-docs